  /*for(i=0;i<ener.size-1;i++)
	{
		for(j=0;j<ener.size-i-1;j++)
		{
			if(ener.data[j]>ener.data[j+1])
			{
				temp=ener.data[j];
				ener.data[j]=ener.data[j+1];
				ener.data[j+1]=temp;
			}
		}
	}
   */